cluster:
  dataset:
    job_name: dataset
    task0:
      task_index: 0
      dataset_name: dataset/sraps
dataset:
  sraps:
    dataset_cls_name: sraps
    image_type: sinogram
    batch_size: 4
    with_poission_noise: false
    log_scale: false
    target_shape: [256, 256]
network:
  srms:
    nb_layers: 10
    