# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recon_pb2 as recon__pb2


class ReconstructionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
<<<<<<< HEAD
    self.ReconStep = channel.stream_stream(
=======
    self.ReconStep = channel.unary_unary(
>>>>>>> d90212f59008ca3fd4572fc7e30fc94fc8d75f6b
        '/Reconstruction/ReconStep',
        request_serializer=recon__pb2.ReconPayload.SerializeToString,
        response_deserializer=recon__pb2.Image.FromString,
        )


class ReconstructionServicer(object):
  # missing associated documentation comment in .proto file
  pass

<<<<<<< HEAD
  def ReconStep(self, request_iterator, context):
=======
  def ReconStep(self, request, context):
>>>>>>> d90212f59008ca3fd4572fc7e30fc94fc8d75f6b
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReconstructionServicer_to_server(servicer, server):
  rpc_method_handlers = {
<<<<<<< HEAD
      'ReconStep': grpc.stream_stream_rpc_method_handler(
=======
      'ReconStep': grpc.unary_unary_rpc_method_handler(
>>>>>>> d90212f59008ca3fd4572fc7e30fc94fc8d75f6b
          servicer.ReconStep,
          request_deserializer=recon__pb2.ReconPayload.FromString,
          response_serializer=recon__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Reconstruction', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
