# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recon.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0brecon.proto\"\x85\x01\n\x0cReconPayload\x12\x1b\n\x13\x65\x66\x66iciency_map_file\x18\x01 \x01(\t\x12\x10\n\x08lor_file\x18\x02 \x01(\t\x12\x11\n\tlor_start\x18\x03 \x01(\x05\x12\x0f\n\x07lor_end\x18\x04 \x01(\x05\x12\r\n\x05image\x18\x05 \x03(\x02\x12\x13\n\x0bimage_shape\x18\x06 \x03(\x05\"\x17\n\x05Image\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\x36\n\x0eReconstruction\x12$\n\tReconStep\x12\r.ReconPayload\x1a\x06.Image\"\x00\x62\x06proto3')
)




_RECONPAYLOAD = _descriptor.Descriptor(
  name='ReconPayload',
  full_name='ReconPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='efficiency_map_file', full_name='ReconPayload.efficiency_map_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lor_file', full_name='ReconPayload.lor_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lor_start', full_name='ReconPayload.lor_start', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lor_end', full_name='ReconPayload.lor_end', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='ReconPayload.image', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_shape', full_name='ReconPayload.image_shape', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=149,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='Image.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['ReconPayload'] = _RECONPAYLOAD
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReconPayload = _reflection.GeneratedProtocolMessageType('ReconPayload', (_message.Message,), dict(
  DESCRIPTOR = _RECONPAYLOAD,
  __module__ = 'recon_pb2'
  # @@protoc_insertion_point(class_scope:ReconPayload)
  ))
_sym_db.RegisterMessage(ReconPayload)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'recon_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)



_RECONSTRUCTION = _descriptor.ServiceDescriptor(
  name='Reconstruction',
  full_name='Reconstruction',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=176,
  serialized_end=230,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReconStep',
    full_name='Reconstruction.ReconStep',
    index=0,
    containing_service=None,
    input_type=_RECONPAYLOAD,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECONSTRUCTION)

DESCRIPTOR.services_by_name['Reconstruction'] = _RECONSTRUCTION

# @@protoc_insertion_point(module_scope)
